In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
X1 = np.array([10, 15, 20, 30, 50, 60, 60, 70]).reshape((-1, 1))  # -1表示未知的行和列数

Y = np.array([0.8, 1.0, 1.8, 2.0, 3.2, 3.0, 3.1, 3.5]).reshape((-1, 1))

In [3]:
X1

array([[10],
       [15],
       [20],
       [30],
       [50],
       [60],
       [60],
       [70]])

In [4]:
Y

array([[0.8],
       [1. ],
       [1.8],
       [2. ],
       [3.2],
       [3. ],
       [3.1],
       [3.5]])

In [5]:
X = np.column_stack((np.ones_like(X1), X1))  # 将两个数组以列的方式组合
X

array([[ 1, 10],
       [ 1, 15],
       [ 1, 20],
       [ 1, 30],
       [ 1, 50],
       [ 1, 60],
       [ 1, 60],
       [ 1, 70]])

In [6]:
X = np.mat(X)  # 将数组转换为矩阵 返回类型为matrix

Y = np.mat(Y)

In [7]:
X

matrix([[ 1, 10],
        [ 1, 15],
        [ 1, 20],
        [ 1, 30],
        [ 1, 50],
        [ 1, 60],
        [ 1, 60],
        [ 1, 70]])

In [8]:
Y

matrix([[0.8],
        [1. ],
        [1.8],
        [2. ],
        [3.2],
        [3. ],
        [3.1],
        [3.5]])

In [9]:
theta = (X.T * X).I * X.T * Y

theta

matrix([[0.5949305 ],
        [0.04330335]])

In [10]:
predict_y = X * theta

predict_y

matrix([[1.02796402],
        [1.24448078],
        [1.46099755],
        [1.89403107],
        [2.76009812],
        [3.19313164],
        [3.19313164],
        [3.62616517]])

In [11]:
mse = mean_squared_error(y_true=np.asarray(Y), y_pred=np.asarray(predict_y)) 
# 输入真实值与预测值的数组形式 不支持矩阵

print("MSE", mse)

MSE 0.06166189697465254


In [12]:
r2 = r2_score(y_true=np.asarray(Y), y_pred=np.asarray(predict_y))

print("r^2", r2)

r^2 0.9356011519846971


In [13]:
x_test = [[1, 55]]

y_test_hat = x_test * theta

print("价格：", y_test_hat)

价格： [[2.97661488]]
